### ISSUE TITLE
Api call issue

### ISSUE THREAD

**Issue by shayan4shayan** [MrApr/Najva-api#1]
Send to all api and send limited api end points are different but in your code you are using same end point for them.
Url for sending notification for all : `https://app.najva.com/api/v1/notifications/`
Url for sending notification with specified token: `https://app.najva.com/notification/api/v1/notifications/`

**Comment by MrApr** [comment]
@shayan4shayan Thanks for bug reporting. 
Bug is fixed now and tested.
